# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-02 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('locale', models.CharField(choices=[('en', 'English'), ('zh', 'Chinese')], default=b'en', max_length=2)),
            ],
            options={
                'ordering': ['code'],
                'db_table': 'block',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'db_table': 'page',
            },
        ),
        migrations.AddField(
            model_name='block',
            name='page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Page'),
        ),
    ]
