# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20170105_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='code',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
